- jekyll/index.html
Make it clearer that we're not settling long-term for anything other than infinite speed. :-P
@devoncarew
> Update "target" lines

- jekyll/css/main.scss
- jekyll/index.html
- run.sh
- use the new cli flags for analysis benchmarks
- include the dart sdk version that we're using to run the analysis
@yjbanov
> fix the analysis dashboard

- bin/build.dart
- pubspec.yaml
> fix data backup logic

- web/analysis.html
- web/index.html
- web/styles.css
Style the footer a bit, and add links to switch between the index and analysis pages.
> add links to switch between pages

- bin/build.dart
- job.plist
- lib/src/buildbot.dart
- lib/src/utils.dart
- pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/3776
> run on green waterfall revisions only

- bin/build.dart
- bin/firebase_to_golem.dart
- lib/src/firebase.dart
- lib/src/utils.dart
> firebase-to-golem sync script

- bin/firebase_to_golem.dart
> un-hardcode connection params in the golem script

- lib/src/refresh.dart
- lib/src/utils.dart
> allow mega gallery to fail

- lib/src/utils.dart
> throw on failure; do not exit

- web/buildbot.js
- web/firebase.js
- web/index.html
- web/styles.css
When the latest waterfall is green but the dashboard build is >8 hours old, display a warning saying "Build out of date!" across the screen.
Fixes https://github.com/flutter/flutter/issues/3687
/cc @devoncarew @sethladd
> Display a warning when waterfall is green but build it too old

- bin/build.dart
- lib/src/utils.dart
- web/firebase.js
Fixes https://github.com/flutter/flutter/issues/3763
/cc @sethladd
> rename build.json to dashboard_bot_status.json

- lib/src/refresh.dart
- lib/src/utils.dart
TBR, fix edit-refresh expectations
> fix edit-refresh expectations

- lib/src/buildbot.dart
- lib/src/refresh.dart
- web/charts.dart
- web/styles.css
- fix the edit/refresh chart (issues constructing the data for the charts, and a NPE with tooltips)
> fix the edit/refresh chart

- bin/build.dart
- pubspec.yaml
@yjbanov, I'm not sure when the dashboard isn't running currently, but this will hopefully make it more resilient to failures in individual benchmarks.
> only fail individual benchmarks

- job.plist
- setup.sh
Fixes https://github.com/flutter/flutter/issues/4013
> upload logs to Google Cloud Storage

- web/firebase.js
> Fix max bar height in transitions benchmark

- bin/build.dart
- lib/src/analysis.dart
- lib/src/framework.dart
- lib/src/gallery.dart
- lib/src/perf_tests.dart
- lib/src/refresh.dart
This sets up infrastructure to fix the multiple dashboard issues.
> introduce Task and TaskRunner; record build status to Firebase

- .travis.yml
Experimenting with pegging the dashboard to dart 1.16.0
> peg the dashboard to dart 1.16.0

- .travis.yml
Simplify how we specify `1.16.0`; @yjbanov.
> specify 1.16.0

- web/charts.dart
- web/charts.html
- add a chart for missing dartdoc docs
- make the charts smaller (so 4 fit on a page)
- reduce the code duplication between the various charts
@yjbanov
> add dartdoc burndown chart

- bin/firebase_to_golem.dart
> fix dashboard status Firebase key

- setup.sh
> fix log acls

- job.plist
- setup.sh
Deleting the file that's already being written to results in errors.
> fix logging

- run.sh
> prevent scripts from killing themselves

- lib/src/gallery.dart
- lib/src/perf_tests.dart
This seems to finally work now. Fixes https://github.com/flutter/flutter/issues/3719
> switch to profile mode

- bin/build.dart
- lib/src/adb.dart
- lib/src/gallery.dart
- lib/src/perf_tests.dart
- lib/src/refresh.dart
- lib/src/utils.dart
- pubspec.yaml
- test/src/adb_test.dart
- test/src/utils_test.dart
- tool/travis.sh
Fixes https://github.com/flutter/flutter/issues/4314
> keep screen off between runs

- lib/src/adb.dart
- test/src/adb_test.dart
Oops. Forgot to actually upload changes I made in response to comments from PR #83
> address comments from PR #83

- bin/build.dart
- lib/src/utils.dart
Fixes https://github.com/flutter/flutter/issues/4490
/cc @devoncarew @mraleph
> use local Flutter repo if there are local changes

- bin/build.dart
- lib/src/golem.dart
> fix benchmark name filtering

- bin/build.dart
Firebase doesn't like keys with dots in them
TBR @devoncarew
> temporarily disable golem_data.json generation

- bin/build.dart
- lib/src/gallery.dart
- web/firebase.js
- web/index.html
> add APK size benchmark for Flutter Gallery app and a card

- bin/build.dart
- job.plist
- lib/src/gallery.dart
- lib/src/size_tests.dart
> measure the size of basic app instead of gallery

- bin/build.dart
- lib/src/analysis.dart
- lib/src/framework.dart
- lib/src/perf_tests.dart
> reorg test list so it is easier to isolate them

- lib/src/golem.dart
> remove unnecessary benchmarks

- web/firebase.js
- web/index.html
> change kb (kilobits) to KB (kilobytes)

- tool/travis.sh
- web/charts.dart
- web/firebase.js
- print some dashboard messages as info level, not warning level (fix https://github.com/flutter/flutter/issues/4698)
- be more resilient to exceptions from the charting code
@yjbanov
> catch and print errors
